version: '3.1'
services:
  postgresql:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_USER: maasuser
      POSTGRES_PASSWORD: maaspwd
      POSTGRES_DB: maasdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: alongpassw0rd